# path related variables
paths:
  raw_data_directory: "data/raw/"
  raw_training_data_directory: "data/training/raw/"
  raw_val_data_directory: "data/validation/raw/"
  raw_test_data_directory: "data/test/raw/"
  processed_training_data_directory: "data/training/processed/"
  featured_training_data_directory: "data/training/featured/"
  processed_test_data_directory: "data/test/processed/"
  featured_test_data_directory: "data/test/featured/"
  processed_val_data_directory: "data/validation/processed/"
  featured_val_data_directory: "data/validation/featured/"
  merged_training_data_directory: "data/training/merged"
  merged_val_data_directory: "data/validation/merged"
  merged_test_data_directory: "data/test/merged"
  preprocessor_directory: "models/preprocessor/"
  report_directory: "reports/"
  model_directory: "models/"
  env_directory: ".env"
  portfolio_directory: "portfolio.csv"
  state_directory: "state.json"

# data related variables
data:
  universe: "NIFTY - "
  selected_tickers: "tickers_nifty_50"
  timeframe: '1d'
  backdate: 200
  max_backtesting_time: 10
  begin_train_date: '2015-07-01'
  begin_val_date: '2024-01-01'
  begin_test_date: '2025-01-01'
  train_val_split: '2023-12-31'
  val_test_split: '2024-12-31'
  end_date: '2025-06-30'

#  nifty - 50
  tickers_nifty_50 :
    - ADANIENT.NS
    - ADANIPORTS.NS
    - APOLLOHOSP.NS
    - ASIANPAINT.NS
    - AXISBANK.NS
    - BAJAJ-AUTO.NS
    - BAJFINANCE.NS
    - BAJAJFINSV.NS
    - BEL.NS
    - BHARTIARTL.NS
    - CIPLA.NS
    - COALINDIA.NS
    - DRREDDY.NS
    - EICHERMOT.NS
    - ETERNAL.NS
    - GRASIM.NS
    - HCLTECH.NS
    - HDFCBANK.NS
    - HDFCLIFE.NS
    - HEROMOTOCO.NS
    - HINDALCO.NS
    - HINDUNILVR.NS
    - ICICIBANK.NS
    - ITC.NS
    - INDUSINDBK.NS
    - INFY.NS
    - JSWSTEEL.NS
    - JIOFIN.NS
    - KOTAKBANK.NS
    - LT.NS
    - M&M.NS
    - MARUTI.NS
    - NTPC.NS
    - NESTLEIND.NS
    - ONGC.NS
    - POWERGRID.NS
    - RELIANCE.NS
    - SBILIFE.NS
    - SHRIRAMFIN.NS
    - SBIN.NS
    - SUNPHARMA.NS
    - TCS.NS
    - TATACONSUM.NS
    - TATAMOTORS.NS
    - TATASTEEL.NS
    - TECHM.NS
    - TITAN.NS
    - TRENT.NS
    - ULTRACEMCO.NS
    - WIPRO.NS

#  nifty - 100
  tickers_nifty_100:
    - ABB.NS
    - ADANIENSOL.NS
    - ADANIENT.NS
    - ADANIGREEN.NS
    - ADANIPORTS.NS
    - ADANIPOWER.NS
    - AMBUJACEM.NS
    - APOLLOHOSP.NS
    - ASIANPAINT.NS
    - DMART.NS
    - AXISBANK.NS
    - BAJAJ-AUTO.NS
    - BAJFINANCE.NS
    - BAJAJFINSV.NS
    - BAJAJHLDNG.NS
    - BAJAJHFL.NS
    - BANKBARODA.NS
    - BEL.NS
    - BPCL.NS
    - BHARTIARTL.NS
    - BOSCHLTD.NS
    - BRITANNIA.NS
    - CGPOWER.NS
    - CANBK.NS
    - CHOLAFIN.NS
    - CIPLA.NS
    - COALINDIA.NS
    - DLF.NS
    - DABUR.NS
    - DIVISLAB.NS
    - DRREDDY.NS
    - EICHERMOT.NS
    - ETERNAL.NS
    - GAIL.NS
    - GODREJCP.NS
    - GRASIM.NS
    - HCLTECH.NS
    - HDFCBANK.NS
    - HDFCLIFE.NS
    - HAVELLS.NS
    - HEROMOTOCO.NS
    - HINDALCO.NS
    - HAL.NS
    - HINDUNILVR.NS
    - HYUNDAI.NS
    - ICICIBANK.NS
    - ICICIGI.NS
    - ICICIPRULI.NS
    - ITC.NS
    - INDHOTEL.NS
    - IOC.NS
    - IRFC.NS
    - INDUSINDBK.NS
    - NAUKRI.NS
    - INFY.NS
    - INDIGO.NS
    - JSWENERGY.NS
    - JSWSTEEL.NS
    - JINDALSTEL.NS
    - JIOFIN.NS
    - KOTAKBANK.NS
    - LTIM.NS
    - LT.NS
    - LICI.NS
    - LODHA.NS
    - M&M.NS
    - MARUTI.NS
    - NTPC.NS
    - NESTLEIND.NS
    - ONGC.NS
    - PIDILITIND.NS
    - PFC.NS
    - POWERGRID.NS
    - PNB.NS
    - RECLTD.NS
    - RELIANCE.NS
    - SBILIFE.NS
    - MOTHERSON.NS
    - SHREECEM.NS
    - SHRIRAMFIN.NS
    - SIEMENS.NS
    - SBIN.NS
    - SUNPHARMA.NS
    - SWIGGY.NS
    - TVSMOTOR.NS
    - TCS.NS
    - TATACONSUM.NS
    - TATAMOTORS.NS
    - TATAPOWER.NS
    - TATASTEEL.NS
    - TECHM.NS
    - TITAN.NS
    - TORNTPHARM.NS
    - TRENT.NS
    - ULTRACEMCO.NS
    - UNITDSPR.NS
    - VBL.NS
    - VEDL.NS
    - WIPRO.NS
    - ZYDUSLIFE.NS

#   nifty - 200
  tickers_nifty_200:
    - ABB.NS
    - ACC.NS
    - APLAPOLLO.NS
    - AUBANK.NS
    - ADANIENSOL.NS
    - ADANIENT.NS
    - ADANIGREEN.NS
    - ADANIPORTS.NS
    - ADANIPOWER.NS
    - ATGL.NS
    - ABCAPITAL.NS
    - ABFRL.NS
    - ALKEM.NS
    - AMBUJACEM.NS
    - APOLLOHOSP.NS
    - APOLLOTYRE.NS
    - ASHOKLEY.NS
    - ASIANPAINT.NS
    - ASTRAL.NS
    - AUROPHARMA.NS
    - DMART.NS
    - AXISBANK.NS
    - BSE.NS
    - BAJAJ-AUTO.NS
    - BAJFINANCE.NS
    - BAJAJFINSV.NS
    - BAJAJHLDNG.NS
    - BAJAJHFL.NS
    - BANDHANBNK.NS
    - BANKBARODA.NS
    - BANKINDIA.NS
    - MAHABANK.NS
    - BDL.NS
    - BEL.NS
    - BHARATFORG.NS
    - BHEL.NS
    - BPCL.NS
    - BHARTIARTL.NS
    - BHARTIHEXA.NS
    - BIOCON.NS
    - BOSCHLTD.NS
    - BRITANNIA.NS
    - CGPOWER.NS
    - CANBK.NS
    - CHOLAFIN.NS
    - CIPLA.NS
    - COALINDIA.NS
    - COCHINSHIP.NS
    - COFORGE.NS
    - COLPAL.NS
    - CONCOR.NS
    - CUMMINSIND.NS
    - DLF.NS
    - DABUR.NS
    - DIVISLAB.NS
    - DIXON.NS
    - DRREDDY.NS
    - EICHERMOT.NS
    - ESCORTS.NS
    - ETERNAL.NS
    - EXIDEIND.NS
    - NYKAA.NS
    - FEDERALBNK.NS
    - GAIL.NS
    - GMRAIRPORT.NS
    - GLENMARK.NS
    - GODREJCP.NS
    - GODREJPROP.NS
    - GRASIM.NS
    - HCLTECH.NS
    - HDFCAMC.NS
    - HDFCBANK.NS
    - HDFCLIFE.NS
    - HAVELLS.NS
    - HEROMOTOCO.NS
    - HINDALCO.NS
    - HAL.NS
    - HINDPETRO.NS
    - HINDUNILVR.NS
    - HINDZINC.NS
    - HUDCO.NS
    - HYUNDAI.NS
    - ICICIBANK.NS
    - ICICIGI.NS
    - ICICIPRULI.NS
    - IDFCFIRSTB.NS
    - IRB.NS
    - ITC.NS
    - INDIANB.NS
    - INDHOTEL.NS
    - IOC.NS
    - IRCTC.NS
    - IRFC.NS
    - IREDA.NS
    - IGL.NS
    - INDUSTOWER.NS
    - INDUSINDBK.NS
    - NAUKRI.NS
    - INFY.NS
    - INDIGO.NS
    - JSWENERGY.NS
    - JSWSTEEL.NS
    - JINDALSTEL.NS
    - JIOFIN.NS
    - JUBLFOOD.NS
    - KPITTECH.NS
    - KALYANKJIL.NS
    - KOTAKBANK.NS
    - LTF.NS
    - LICHSGFIN.NS
    - LTIM.NS
    - LT.NS
    - LICI.NS
    - LUPIN.NS
    - MRF.NS
    - LODHA.NS
    - M&MFIN.NS
    - M&M.NS
    - MANKIND.NS
    - MARICO.NS
    - MARUTI.NS
    - MFSL.NS
    - MAXHEALTH.NS
    - MAZDOCK.NS
    - MOTILALOFS.NS
    - MPHASIS.NS
    - MUTHOOTFIN.NS
    - NHPC.NS
    - NMDC.NS
    - NTPCGREEN.NS
    - NTPC.NS
    - NATIONALUM.NS
    - NESTLEIND.NS
    - OBEROIRLTY.NS
    - ONGC.NS
    - OIL.NS
    - OLAELEC.NS
    - PAYTM.NS
    - OFSS.NS
    - POLICYBZR.NS
    - PIIND.NS
    - PAGEIND.NS
    - PATANJALI.NS
    - PERSISTENT.NS
    - PETRONET.NS
    - PHOENIXLTD.NS
    - PIDILITIND.NS
    - POLYCAB.NS
    - PFC.NS
    - POWERGRID.NS
    - PREMIERENE.NS
    - PRESTIGE.NS
    - PNB.NS
    - RECLTD.NS
    - RVNL.NS
    - RELIANCE.NS
    - SBICARD.NS
    - SBILIFE.NS
    - SJVN.NS
    - SRF.NS
    - MOTHERSON.NS
    - SHREECEM.NS
    - SHRIRAMFIN.NS
    - SIEMENS.NS
    - SOLARINDS.NS
    - SONACOMS.NS
    - SBIN.NS
    - SAIL.NS
    - SUNPHARMA.NS
    - SUPREMEIND.NS
    - SUZLON.NS
    - SWIGGY.NS
    - TVSMOTOR.NS
    - TATACOMM.NS
    - TCS.NS
    - TATACONSUM.NS
    - TATAELXSI.NS
    - TATAMOTORS.NS
    - TATAPOWER.NS
    - TATASTEEL.NS
    - TATATECH.NS
    - TECHM.NS
    - TITAN.NS
    - TORNTPHARM.NS
    - TORNTPOWER.NS
    - TRENT.NS
    - TIINDIA.NS
    - UPL.NS
    - ULTRACEMCO.NS
    - UNIONBANK.NS
    - UNITDSPR.NS
    - VBL.NS
    - VEDL.NS
    - VMM.NS
    - IDEA.NS
    - VOLTAS.NS
    - WAAREEENER.NS
    - WIPRO.NS
    - YESBANK.NS
    - ZYDUSLIFE.NS